openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /user/:
    get:
      operationId: listUsers
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
          description: ''
      tags:
      - user
    post:
      operationId: createUser
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - user
  /user/{id}/:
    get:
      operationId: retrieveUser
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this user.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - user
    put:
      operationId: updateUser
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this user.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - user
    patch:
      operationId: partialUpdateUser
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this user.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - user
    delete:
      operationId: destroyUser
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this user.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - user
  /accounts/:
    get:
      operationId: listAccountDetails
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountDetails'
          description: ''
      tags:
      - accounts
    post:
      operationId: createAccountDetails
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountDetails'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AccountDetails'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AccountDetails'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDetails'
          description: ''
      tags:
      - accounts
  /accounts/{user_id}/:
    get:
      operationId: retrieveAccountDetails
      description: ''
      parameters:
      - name: user_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDetails'
          description: ''
      tags:
      - accounts
    put:
      operationId: updateAccountDetails
      description: ''
      parameters:
      - name: user_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountDetails'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AccountDetails'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AccountDetails'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDetails'
          description: ''
      tags:
      - accounts
    patch:
      operationId: partialUpdateAccountDetails
      description: ''
      parameters:
      - name: user_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountDetails'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AccountDetails'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AccountDetails'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDetails'
          description: ''
      tags:
      - accounts
    delete:
      operationId: destroyAccountDetails
      description: ''
      parameters:
      - name: user_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - accounts
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        last_login:
          type: string
          format: date-time
          readOnly: true
        is_superuser:
          type: boolean
          readOnly: true
          description: Designates that this user has all permissions without explicitly
            assigning them.
        is_staff:
          type: boolean
          readOnly: true
          description: Designates whether the user can log into this admin site.
        is_active:
          type: boolean
          readOnly: true
          description: Designates whether this user should be treated as active. Unselect
            this instead of deleting accounts.
        date_joined:
          type: string
          format: date-time
        email:
          type: string
          format: email
          maxLength: 200
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        bvn:
          type: integer
          nullable: true
        groups:
          type: array
          items:
            type: string
          readOnly: true
          description: The groups this user belongs to. A user will get all permissions
            granted to each of their groups.
        user_permissions:
          type: array
          items:
            type: string
          readOnly: true
          description: Specific permissions for this user.
      required:
      - email
      - first_name
      - last_name
    AccountDetails:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user:
          type: object
          properties:
            id:
              type: integer
              readOnly: true
            last_login:
              type: string
              format: date-time
              readOnly: true
            is_superuser:
              type: boolean
              readOnly: true
              description: Designates that this user has all permissions without explicitly
                assigning them.
            is_staff:
              type: boolean
              readOnly: true
              description: Designates whether the user can log into this admin site.
            is_active:
              type: boolean
              readOnly: true
              description: Designates whether this user should be treated as active.
                Unselect this instead of deleting accounts.
            date_joined:
              type: string
              format: date-time
            email:
              type: string
              format: email
              maxLength: 200
            first_name:
              type: string
              maxLength: 150
            last_name:
              type: string
              maxLength: 150
            bvn:
              type: integer
              nullable: true
            groups:
              type: array
              items:
                type: string
              readOnly: true
              description: The groups this user belongs to. A user will get all permissions
                granted to each of their groups.
            user_permissions:
              type: array
              items:
                type: string
              readOnly: true
              description: Specific permissions for this user.
          required:
          - email
          - first_name
          - last_name
          readOnly: true
        bank_details:
          type: object
          properties:
            id:
              type: integer
              readOnly: true
            name:
              type: string
              maxLength: 200
            bank_code:
              type: string
              maxLength: 20
            credit_card:
              type: integer
              nullable: true
          required:
          - name
          - bank_code
          readOnly: true
        account_balance:
          type: number
          readOnly: true
