# Generated by Django 3.2.4 on 2021-06-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210630_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bvn',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
