# Generated by Django 3.2.4 on 2021-06-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_user_bvn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bvn',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
