# Generated by Django 3.2.4 on 2021-06-30 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bank_code', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'bank_details',
                'db_table': 'bank_details',
            },
        ),
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bvn', models.IntegerField()),
                ('account_balance', models.FloatField(blank=True)),
                ('bank_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_details', to='finances.bankdetails')),
            ],
            options={
                'verbose_name_plural': 'account_details',
                'db_table': 'account_details',
            },
        ),
    ]
