# Generated by Django 3.2.4 on 2021-06-30 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_accountdetails_account_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('card_no', models.IntegerField()),
                ('check_code', models.IntegerField(max_length=3)),
                ('pin', models.IntegerField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'credit_cards',
                'db_table': 'credit_cards',
            },
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='credit_card',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_details', to='finances.creditcards'),
        ),
    ]
