# Generated by Django 3.2.4 on 2021-07-01 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_auto_20210630_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 5, 21, 43, 359224)),
        ),
    ]
