# Generated by Django 3.2.4 on 2021-07-02 13:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_alter_transactionhistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 13, 38, 41, 834012, tzinfo=utc)),
        ),
    ]
