# Generated by Django 3.2.4 on 2021-07-02 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_alter_transactionhistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
